version: "3.8"

services:

  app:
    build: .
    ports:
      - "3001:3001"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:4.4
    logging:
      driver: "none"
    environment:
      TZ: "${TZ}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    volumes:
      - ./mongodata:/data/db
    ports:
      - ${MONGO_EXT_PORT}:27017

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - app